### PR TITLE
Improve Archived-At header availability/info

### PR DESCRIPTION
**Pull request by BigBlueHat**
Relates to #144

I'd also like to link the value, but wasn't sure how you'd prefer me do that. Can I just create the link in place? or would you like a utility function (presumably in Strings.js) for future use?

### CODE REVIEW

**Comment by stephenegriffin** [comment]
linking sounds scary - this is potentially hostile data correct? It might be preferable that if someone wants to follow the link they should have to take explicit action.

If you do explore it - yes - doing it in a general fashion would be preferable to having a hard coded special case.

**Comment by BigBlueHat** [comment]
Yeah. Potentially as it's set by the sending mailing list software (or something pretending to be that). As a precaution, I'd set the link's text to be the same as the `href` of the link. It wouldn't be any more or less safe than displaying the text for copy/paste...just...faster.

**Comment by BigBlueHat** [comment]
I've not had a chance to test this, so I'm not sure if `new URL()` is feasible in Outlook...but if it is, this should be ready to go. 😸

**Comment by stephenegriffin** [comment]
Continued over in #153 with my changes

**Pull request closed without merging**
