### PR TITLE
Android support and more flexibility for deployment

### PR DESCRIPTION
**Pull request by mitchcapper**
I don't like big multi-feature commits but it took a bit to go through and get it working for android.  I am a bit short on time so didn't want to go back and parse each into a feature, especially as I needed multiple in one branch to be able to build.

Assuming this is acceptable do not merge yet, I will do some work on the android UI still but wanted to get the mega commit up and done with some notes.

unit tests still are not 100% on non eastern timezone machines but closer.

I did some testing but as I switched all URLs to relative it is more error prone, so far haven't found any breakage.

I realize this is going to screw with #220 which is some massive TS conversion but as it has been waiting a bit I figured I would get this in.

### CODE REVIEW

**Comment by stephenegriffin** [comment]
Thanks for doing this work - mind if I cherry pick a bit into features so I can be sure we don't break desktop and ios along the way?

**Comment by mitchcapper** [comment]
100% fine,  just give me another day or two to add the UI changes.   I did separate it out into android vs ios now and virtually all the ios/desktop code will remain unchanged.

**Comment by stephenegriffin** [comment]
Finally got some time to start looking at this - why switch all the paths to '..'?

**Comment by mitchcapper** [comment]
Sorry I realize I didn't commit up the other ui changes I will try to do so this week.  I made all the paths relative in case it is not hosted on the root of a domain:)

**Comment by stephenegriffin** [comment]
> Sorry I realize I didn't commit up the other ui changes I will try to do so this week. I made all the paths relative in case it is not hosted on the root of a domain:)

Sounds fair - I'll factor this out so it's easier to see the android specific changes.

**Comment by stephenegriffin** [comment]
Now that I've finished converting to webpack I'm gonna take another crack at getting these changes merged in - may be easier to hand port them to a new branch tho

**Pull request merged**
